function Mock () {
    return {
        
        fields : [
            {
                id: "tags",
                title: "Tags",
                type: "multiSelect",
                required: false,
                predefinedValues: []
            },
            {
                id: "brand",
                title: "Brand",
                type: "Text",
                required: false,
                predefinedValues:  [
                    "Will",
                    "be",
                    "like",
                    "top",
                    "ten",
                    "maybe"
                ]
            },
            {
                id: "channel",
                title: "Channel",
                type: "select",
                required: true,
                predefinedValues:  [
                    "Not Appicable",
                    "Other",
                    "Business to Business",
                    "Convenience",
                    "Department",
                    "Direct to Consumer",
                    "Discount",
                    "Drug",
                    "Foodservice",
                    "General Trade",
                    "Home Improvement",
                    "Independent",
                    "Institution",
                    "Online",
                    "Pharmacy",
                    "Specialty",
                    "Supermarket",
                    "Superstore",
                    "University and School",
                    "Wholesale",
                    "Multiple"
                ]
            },
            {
                id: "client",
                title: "Client",
                type: "text",
                required: false,
                predefinedValues:  []
            },
            {
                id: "country_or_region",
                title: "Country Or Region",
                type: "select",
                required: true,
                predefinedValues:  [
                    "Global",
                    "Greater Africa",
                    "Middle East South Asia",
                    "Asia Pacific",
                    "KSA",
                    "Latin America",
                    "MESA",
                    "North America",
                    "Europe",
                    "Angola",
                    "Australia",
                    "Botswana",
                    "Brazil",
                    "Cambodia",
                    "China",
                    "Eswatini",
                    "Eswatini",
                    "Ethiopia",
                    "Germany",
                    "Hong Kong",
                    "India",
                    "Indonesia",
                    "Kenya",
                    "Malawi",
                    "Malaysia",
                    "Mauritius",
                    "Morocco",
                    "Mozambique",
                    "Myanmar",
                    "Netherlands",
                    "Pakistan",
                    "Portugal",
                    "Singapore",
                    "South Africa",
                    "Taiwan",
                    "Tanzania",
                    "Thailand",
                    "UAE",
                    "UK",
                    "USA",
                    "Vietnam",
                    "Zambia",
                    "Zimbabwe"
                ]
            },
            {
                id: "document_type",
                title: "Document Type",
                type: "select",
                required: true,
                predefinedValues:  [
                    "Brand Assets",
                    "Brief and Qualify",
                    "Case Study",
                    "Company Profiles",
                    "Costing and Negotiation",
                    "Credential",
                    "Education Material",
                    "Learning and Development",
                    "Learnings",
                    "Legal and Compliance",
                    "Marketing Collateral",
                    "Operations",
                    "People",
                    "Proposal",
                    "Sales Collateral",
                    "Sales Support",
                    "Service Profiles",
                    "Technology and Data",
                    "Value Proposition"
                ]
            },
            {
                id: "industry",
                title: "Industry",
                type: "multiSelect",
                required: true,
                predefinedValues:  [
                    "Not Applicable",
                    "Adult Beverages",
                    "Automotive",
                    "CE, Technology & Telco",
                    "Consumer Packaged Goods",
                    "Durable Goods",
                    "Entertainment",
                    "Amusement & Recreation",
                    "Apparel, Footwear & Accesories",
                    "Arts & Crafts",
                    "Automotive",
                    "Baby",
                    "Bakery",
                    "Banking",
                    "Beverages",
                    "Builder, Construction, Real Estate",
                    "Candy & Confections",
                    "CE, Technology & Telco",
                    "Chemicals & Flavor Ingredients",
                    "Commercial-Grade Supplies",
                    "Consumer Electronics",
                    "Consumer Packaged Goods",
                    "Cruise Lines",
                    "Dairy/Dairy Alternatives",
                    "Dealership",
                    "Deli",
                    "Distributor",
                    "Durable Goods",
                    "Education",
                    "Entertainment",
                    "Entertainment, Broadcasting, Streaming Services",
                    "Fast Casual",
                    "Financial Services",
                    "Fitness",
                    "Foodservice",
                    "Fresh (Meat, Meat Alternatives, Poultry, Seafood, Eggs)",
                    "Frozen Foods",
                    "Gaming",
                    "Government Agency",
                    "Health & Wellness",
                    "Health, Beauty, Personal Care",
                    "Healthcare",
                    "Home Appliances",
                    "Home Furnishings & Residential Construction Goods",
                    "Hotels & Lodging",
                    "Household Products",
                    "Housewares",
                    "Industrial Equipment",
                    "Insurance",
                    "Investment",
                    "Lawn, Garden, Pest Control Products",
                    "Legal/Consulting",
                    "Motorcycles & Off-Roading Vehicles",
                    "Non-Profit Organization",
                    "OEM (Original Equipment Manufacturer)",
                    "Office Supplies, Stationary, Greeting Cards",
                    "Pantry (Dry Goods, Cans, Pasta, Spices, Baking)",
                    "Pet Care",
                    "Pet Care/Veterinary Services",
                    "Pharmaceuticals (RX or OTC)",
                    "Private Equity/Holding Co.",
                    "Produce",
                    "Professional Services",
                    "Publishing & Media",
                    "QSR",
                    "Recreational Boating",
                    "Rental Cars",
                    "Restaurant & Bars",
                    "Retail",
                    "Retail : Petrol Forecourt Sations",
                    "Retail: Baby/Children",
                    "Retail: Beauty",
                    "Retail: Club",
                    "Retail: Consumer Electronics",
                    "Retail: Convenience",
                    "Retail: Department",
                    "Retail: Dollar/Value",
                    "Retail: Drug",
                    "Retail: E-Commerce",
                    "Retail: Fashion & Apparel",
                    "Retail: Grocery",
                    "Retail: Health, Supplements, etc.",
                    "Retail: Hispanic Grocery",
                    "Retail: Home Goods",
                    "Retail: Home Improvement",
                    "Retail: Mass",
                    "Retail: Military",
                    "Retail: Natural Specialty",
                    "Retail: Office",
                    "Retail: Pet",
                    "Retail: Specialty",
                    "Retail: Sporting Goods & Active Lifestyle",
                    "Retail: Wholesaler",
                    "Retail: Wholesaler (not Club)",
                    "Retail: Wine & Liquor",
                    "Snacking & Shelf Stable Breakfast",
                    "Sports & Recreation Goods",
                    "Technology",
                    "Telecommunications",
                    "Tobacco & Regulated",
                    "Tools, Lawn & Garden Equipment",
                    "Toys",
                    "Travel & Leisure",
                    "Travel Services",
                    "Utilities",
                    "Vitamins & Supplements",
                    "Wholesaler"
                ]
            },
            {
                id: "partner",
                title: "Partner",
                type: "text",
                required: false,
                predefinedValues:  [


                    
                ]
            },
            {
                id: "primary_service",
                title: "Primary Service",
                type: "select",
                required: true,
                predefinedValues:  [
                    "Not Applicable",
                    "Field Sales & Merchandising",
                    "Retail Operations",
                    "E-Commerce",
                    "Headquarter Sales",
                    "Brand Development & Design",
                    "Consumer & Shopper Marketing",
                    "Digital Marketing & Media",
                    "Experiential Marketing",
                    "Channel & Category Strategy",
                    "Data Strategy & Development",
                    "Business Intelligence & Insights",
                    "Retail Optimization",
                    "Intelligent Content Syndication",
                    "Logistics & Production",
                    "Experience Management",
                    "Talent Acquisition",
                    "Learning & Development",
                    "Employee Engagement",
                    "Business process outsourcing"
                ]
            },
            {
                id: "relevant_year",
                title: "Relevant Year",
                type: "select",
                required: true,
                predefinedValues:  [
                    "2010",
                    "2011",
                    "2012",
                    "2013",
                    "2014",
                    "2015",
                    "2016",
                    "2017",
                    "2018",
                    "2019",
                    "2020",
                    "2021",
                    "2022",
                    "2023",
                    "2024",
                    "2025"
                ]
            },
            {
                id: "security_access",
                title: "Security Access",
                type: "multiSelect",
                required: true,
                predefinedValues:  [
                    "Global",
                    "Greater Africa",
                    "Middle East South Asia",
                    "Asia Pacific",
                    "KSA",
                    "Latin America",
                    "MESA",
                    "North America",
                    "Europe",
                    "Angola",
                    "Australia",
                    "Botswana",
                    "Brazil",
                    "Cambodia",
                    "China",
                    "Eswatini",
                    "Eswatini",
                    "Ethiopia",
                    "Germany",
                    "Hong Kong",
                    "India",
                    "Indonesia",
                    "Kenya",
                    "Malawi",
                    "Malaysia",
                    "Mauritius",
                    "Morocco",
                    "Mozambique",
                    "Myanmar",
                    "Netherlands",
                    "Pakistan",
                    "Portugal",
                    "Singapore",
                    "South Africa",
                    "Taiwan",
                    "Tanzania",
                    "Thailand",
                    "UAE",
                    "UK",
                    "USA",
                    "Vietnam",
                    "Zambia",
                    "Zimbabwe"
                ]
            },
            {
                id: "service",
                title: "Service",
                type: "select",
                required: true,
                predefinedValues:  [
                    "Not Applicable - Other",
                    "Brand Development & Design",
                    "Brand Development & Design - POS Execution",
                    "Business Intelligence & Insights",
                    "Business Intelligence & Insights - Analytics",
                    "Business Intelligence & Insights - Business Insights",
                    "Business Intelligence & Insights - Mobility",
                    "Business Intelligence & Insights - Research",
                    "Business Process Outsourcing",
                    "Business Process Outsourcing - BPO",
                    "Business Process Outsourcing - CIC",
                    "Channel & Category Strategy",
                    "Channel & Category Strategy - Category Strategy",
                    "Channel & Category Strategy - Marketing Strategy",
                    "Channel & Category Strategy - Route To Market",
                    "Consumer & Shopper Marketing",
                    "Consumer & Shopper Marketing - Activations",
                    "Consumer & Shopper Marketing - Alternative Sampling",
                    "Consumer & Shopper Marketing - Brand Ambassador",
                    "Consumer & Shopper Marketing - Influencer Marketing",
                    "Consumer & Shopper Marketing - Shopper Engagement",
                    "Data Strategy & Development",
                    "Data Strategy & Development - Data Strategy & Development",
                    "Digital Marketing & Media",
                    "Digital Marketing & Media - Digital Marketing",
                    "Digital Marketing & Media - Media Management",
                    "E-Commerce",
                    "E-Commerce - 1P",
                    "E-Commerce - 3P",
                    "E-Commerce -1P/3P",
                    "Employee Engagement",
                    "Employee Engagement - Employee Engagement",
                    "Experience Management - Auditing",
                    "Experience Management - Compliance",
                    "Experience Management - Mystery Shopper",
                    "Experintial Marketing",
                    "Experintial Marketing - Assisted Selling",
                    "Experintial Marketing - ATL Creative",
                    "Experintial Marketing - Brand Experiential",
                    "Experintial Marketing - Retail Experiential",
                    "Field Sales & Merchandising",
                    "Field Sales & Merchandising - Alternative Sales",
                    "Field Sales & Merchandising - B2B Sales",
                    "Field Sales & Merchandising - Distribution",
                    "Field Sales & Merchandising - Field Sales",
                    "Field Sales & Merchandising - Key Account Management",
                    "Field Sales & Merchandising - Merchandising",
                    "Field Sales & Merchandising - Surge Merchandising",
                    "Headquarter Sales",
                    "Headquarter Sales - Telesales",
                    "Intelligent Content Syndication",
                    "Intelligent Content Syndication - Data Aggregation and Syndication",
                    "Learning & Development",
                    "Learning & Development - L&D",
                    "Logisitics & Production",
                    "Logisitics & Production - Distribution",
                    "Logisitics & Production - GEM",
                    "Logisitics & Production - Installations",
                    "Logisitics & Production - Logistics",
                    "Logisitics & Production - POS, Logistics",
                    "Logisitics & Production - Reverse Logistics",
                    "Logisitics & Production - Warehousing",
                    "Retail Operations",
                    "Retail Operations - Retail Operations",
                    "Retail Operations - Shop Management",
                    "Retail Optimization",
                    "Retail Optimization - Image Recognition",
                    "Retail Optimization - Robotics",
                    "Retail Optimization - Supply Chain",
                    "Talent Acquisition",
                    "Talent Acquisition - Recruitment"
                ]
            },
        ],

        retrieveFields : function () {
            return this.fields
        },

        uploadDocumentSuccess : function () {
            return {
                "status" : 200,
                "message" : "Document uploaded successfully"
            }
        },

        uploadDocumentValidationFailure : function () {
            return {
                "status" : 400,
                "message" : "Validation Failed",
                "errors" : [
                    {"fieldId" : "service", "message" : "This field is required" },
                    {"fieldId" : "partner", "message" : "Field cannot contain emojis? 😡" },
                ]
            }
        },

        uploadDocumentServerFailure : function () {
            return {
                "status" : 500,
                "message" : "Server Error",
            }
        }
    }
}